### ISSUE TITLE
some problems running quickcheck

### ISSUE THREAD

**Issue by eskuai** [jepsen-io/local-fs#2]
Hello,

I am trying to run local-fs test using:

``lein run quickcheck``

but, i a, doing something wrong, because i got:

```
rm: refusing to remove '.' or '..' directory: skipping 'data/.'
rm: refusing to remove '.' or '..' directory: skipping 'data/..'
```

and

```
ERROR [2022-08-02 08:23:36,763] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```

vagrant instance running

```
[vagrant@fedora local-fs]$ uname -a
Linux fedora 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@fedora local-fs]$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (Red_Hat-17.0.4.0.8-1.fc36) (build 17.0.4+8)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.0.8-1.fc36) (build 17.0.4+8, mixed mode, sharing)
[vagrant@fedora local-fs]$
```

Full stacktrace:

```
[vagrant@fedora local-fs]$ lein run quickcheck
08:23:33.578 [main] INFO jepsen.local-fs - Beginning quickcheck trials of 0-operation history
INFO [2022-08-02 08:23:33,705] jepsen test runner - jepsen.core Test version f66798b5ce20829702226a3e6d82697ca47bd759
INFO [2022-08-02 08:23:33,705] jepsen test runner - jepsen.core Command line:
lein run quickcheck
INFO [2022-08-02 08:23:33,749] jepsen test runner - jepsen.core Running test:
{:remote
 #jepsen.control.retry.Remote{:remote #jepsen.control.scp.Remote{:cmd-remote #jepsen.control.sshj.SSHJRemote{:concurrency-limit 6,
                                                                                                             :conn-spec nil,
                                                                                                             :client nil,
                                                                                                             :semaphore nil},
                                                                 :conn-spec nil},
                              :conn nil}
 :concurrency 1
 :dir "data"
 :db
 #object[jepsen.local_fs.db.dir$db$reify__1536
         "0x65b1693c"
         "jepsen.local_fs.db.dir$db$reify__1536@65b1693c"]
 :name "shell dir"
 :start-time
 #object[org.joda.time.DateTime "0x9a74a93" "2022-08-02T08:23:33.655Z"]
 :net
 #object[jepsen.net$reify__10223 "0x255d4d7" "jepsen.net$reify__10223@255d4d7"]
 :client #jepsen.local_fs.shell.client.FSClient{:dir "data"}
 :barrier
 #object[java.util.concurrent.CyclicBarrier
         "0x426bf2f2"
         "java.util.concurrent.CyclicBarrier@426bf2f2"]
 :ssh {:dummy? true}
 :checker
 #object[jepsen.checker$compose$reify__9724
         "0x2cfd9b0a"
         "jepsen.checker$compose$reify__9724@2cfd9b0a"]
 :argv ("quickcheck")
 :nemesis #unprintable "jepsen.nemesis$reify__10326@1f3dafd4"
 :nodes ["local"]
 :generator
 (jepsen.generator.OnThreads
  {:f #object[clojure.core$complement$fn__5737
              "0x1802f60c"
              "clojure.core$complement$fn__5737@1802f60c"],
   :gen []})
 :os #object[jepsen.os$reify__2799 "0x3fcb737" "jepsen.os$reify__2799@3fcb737"]
 :time-limit 60
 :quickcheck-scour 1}

INFO [2022-08-02 08:23:36,744] jepsen test runner - jepsen.db Tearing down DB
WARN [2022-08-02 08:23:36,760] jepsen test runner - jepsen.core Test crashed!
clojure.lang.ExceptionInfo: Shell command ("bash" "-c" "rm -rf data/* data/.*") returned exit status 1

rm: refusing to remove '.' or '..' directory: skipping 'data/.'
rm: refusing to remove '.' or '..' directory: skipping 'data/..'

        at slingshot.support$stack_trace.invoke(support.clj:201)
        at jepsen.local_fs.util$sh_STAR_.invokeStatic(util.clj:51)
        at jepsen.local_fs.util$sh_STAR_.doInvoke(util.clj:34)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at jepsen.local_fs.util$sh.invokeStatic(util.clj:61)
        at jepsen.local_fs.util$sh.doInvoke(util.clj:58)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at jepsen.local_fs.db.dir$db$reify__1536.teardown_BANG_(dir.clj:18)
        at jepsen.db$fn__6968$G__6949__6972.invoke(db.clj:12)
        at jepsen.db$fn__6968$G__6948__6977.invoke(db.clj:12)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at jepsen.control$on_nodes$fn__6824.invoke(control.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at dom_top.core$real_pmap_helper$build_thread__406$fn__407.invoke(core.clj:152)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:833)

ERROR [2022-08-02 08:23:36,763] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1262)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
        at clojure.string$split.invokeStatic(string.clj:225)
        at clojure.string$split.invoke(string.clj:219)
        at jepsen.local_fs$run__1821.invokeStatic(local_fs.clj:194)
        at jepsen.local_fs$run__1821.invoke(local_fs.clj:180)
        at jepsen.cli$run_BANG_.invokeStatic(cli.clj:329)
        at jepsen.cli$run_BANG_.invoke(cli.clj:258)
        at jepsen.local_fs$_main.invokeStatic(local_fs.clj:205)
        at jepsen.local_fs$_main.doInvoke(local_fs.clj:201)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:384)
        at user$eval140.invokeStatic(form-init16603353793367487686.clj:1)
        at user$eval140.invoke(form-init16603353793367487686.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7184)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.Compiler.loadFile(Compiler.java:7591)
        at clojure.main$load_script.invokeStatic(main.clj:475)
        at clojure.main$init_opt.invokeStatic(main.clj:477)
        at clojure.main$init_opt.invoke(main.clj:477)
        at clojure.main$initialize.invokeStatic(main.clj:508)
        at clojure.main$null_opt.invokeStatic(main.clj:542)
        at clojure.main$null_opt.invoke(main.clj:539)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
```

**Comment by eskuai** [comment]
sorry, pr in course
